apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: ashenjay/sms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: boardgame-helper-1
          image: ashenjay/phpmyadmin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
        - name: boardgame-helper-2
          image: ashenjay/console:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
    - protocol: "TCP"
      port: 81
      targetPort: 8081
    - protocol: "TCP"
      port: 82
      targetPort: 8082
  type: LoadBalancer
